components:
  schemas:
    Issue:
      type: object
      properties:
        _id: 
          type: string
        projectId: 
          description: 프로젝트 정보를 불러온다.
          type: object
        errorName: 
          type: string
        errorMessage:
          type: string
        isResolved: 
          type: boolean
        createdAt:
          type: string
        updateAt:
          type: string
        comments: 
          type: array
          items: 
            type: string
        events:
          type: array
          items:
            $ref: '#components/schemas/Event'
paths:
  /api/issue/{issueId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Issue
      summary: 특정 이벤트 정보를 불러온다.
      parameters:
        - name: issueId
          in: path
          required: true
          description: 이슈 아이디 입력
          schema:
            type : string
      responses:
        200:
          description: 이슈 정보 출력
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'